DROP DATABASE IF EXITS BDPrestamo;
CREATE DATABASE BDPrestamo;

USE BDPrestamo;
CREATE TABLE CLIENTE
(COD_CLI INT AUTO_INCREMENT PRIMARY KEY,
NOM_CLI VARCHAR(50),
APE_CLI VARCHAR(50),
DNI_CLI CHAR(8)
);
INSERT INTO CLIENTE VALUES(NULL,'JOSE','TIZNADO','12345678');
INSERT INTO CLIENTE VALUES(NULL,'LUIS','HUAYMAN','12345678');
INSERT INTO CLIENTE VALUES(NULL,'PEDRO','MELGAREJO','12345678');
INSERT INTO CLIENTE VALUES(NULL,'MARIA','SOTO','12345678');

SELECT * FROM CLIENTE;


DROP PROCEDURE IF EXISTS SP_BUSDEL_CLIENTE;
DELIMITER$$
CREATE PROCEDURE SP_BUSDEL_CLIENTE
(BUS VARCHAR(20),TIPO VARCHAR(3))
BEGIN
IF TIPO='B' THEN
SELECT * FROM CLIENTE WHERE COD_CLI=BUS OR NOM_CLI LIKE CONCAT('%',BUS,'%');
ELSE IF TIPO='D' THEN
DELETE FROM CLIENTE WHERE COD_CLI=BUS;
END IF;
END$$
DELIMITER $$
call SP_BUSDEL_CLIENTE('','B')